# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc
# for examples


# append to the history file, don't overwrite it



# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi

# tex live
export MANPATH=$MANPATH:/usr/local/texlive/2021/texmf-dist/doc/man
export INFOPATH=$INFOPATH:/usr/local/texlive/2021/texmf-dist/doc/info
export PATH=$PATH:/usr/local/texlive/2021/bin/x86_64-linux


